graph LR;
    A["`InitializeRepository.ps1`"]--> B;
    B["`Repository definition`"]--> C["`DevOps Extension`"];
    J["`manage-automationAccount`"]-->C;
    k["`manage-automationWebHook`"]-->C;
    B-->D["`Modules`"];
    B-->E["`Schedules`"];
    B-->F["`Runbooks`"];
    B-->G["`Job Schedules`"];
    B-->H["`Configurations`"];
    B-->I["`WebHooks`"];
    L["`Properties`"]-->C;
    M["`Project DIR`"]-->L;
    N["`Subscribtion`"]-->L;
    O["`Azure Subscribtion`"]-->L;
    P["`Resource Group`"]-->L;
    Q["`Automation Account`"]-->L;
    D-->J;
    E-->J;
    F-->J;
    G-->J;
    H-->J;
    I-->k;
    C-- 'sync' ---R["`Azure Automation`"];
