name: Build and Publish VSIX - Manage-AutomationAccount - azure pipeline task
on:
  push:
    branches:
      - master
    paths:
      - 'ManageAutomationAccountV2DevOpsTask/task.json'
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.x'
    - name: Install Node.js
      run: |
        choco install nodejs -y
    - name: Install tfx-cli
      run: |
        npm install -g tfx-cli
    - name: Generate and Upload VSIX file
      env:
        NODE_AUTH_TOKEN: ${{ secrets.PAT_ROMAN_MANAGE_AUTOMATION_ACCOUNT }}
      run: |
        Write-Host "Start generate and upload VSIX file..."
        tfx extension publish --publisher GreyCorbelSolutions --manifest-globs vss-extension.json --token $env:NODE_AUTH_TOKEN --rev-version
